replicaCount: 2

image:
  repository: ghcr.io/nivek-z/cicd-test
  tag: 0869cf2b9de460c2add4b5acf29e057c99ab1e6d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
