replicaCount: 2

image:
  repository: ghcr.io/nivek-z/cicd-test
  tag: 9ab78fa164cc853558977fab55723d87cb27ece4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
